steps:
  # Step 1: Install dependencies using the official Node 18 image
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 2: Build the Next.js application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

# Optional: specify options like logging
options:
  logging: CLOUD_LOGGING_ONLY